import torch

MODELS = {'vgg11',
        'vgg11_bn',
        'vgg13',
        'vgg13_bn',
        'vgg16', 
        'vgg16_bn',
        'vgg19', 
        'vgg19_bn',
        'efficientnet_b0', 
        'efficientnet_b1',
        'efficientnet_b2',
        'efficientnet_b3',
        'efficientnet_b4',
        'efficientnet_b5',
        'efficientnet_b6',
        'efficientnet_b7',
        'efficientnet_v2_l',
        'efficientnet_v2_m',
        'efficientnet_v2_s',
        'convnext_tiny',
        'convnext_small',
        'convnext_base',
        'convnext_large',
        'mobilenet_v2',
        'mobilenet_v3_small',
        'mobilenet_v3_large',
        'vit_b_16',
        'vit_b_32',
        'vit_l_16',
        'vit_l_32',
        'maxvit_t',
        'mnasnet0_5',
        'mnasnet0_75',
        'mnasnet1_0',
        'mnasnet1_3',
    }

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
FLOATING_POINT = torch.float32
ENCODING = 'ascii'